### ISSUE TITLE
No matching distribution found for pyanova

### ISSUE THREAD

**Issue by thefinalwolf** [c3V6a2Vy/pyanova#1]
It seems pyanova isn't able to be found using pip.

`pip install pyanova`

> Collecting pyanova
> Could not find a version that satisfies the requirement pyanova (from versions: )
> No matching distribution found for pyanova

**Comment by c3V6a2Vy** [comment]
hi, sorry for the late reply, pyanova 0.1.1 is available now, you can install via

```
pip install pyanova
```
