### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by wsidl** [c3V6a2Vy/pyanova#5]
Python2 is being deprecated and this library uses unicode methods for string handling in the other packages. Better clean that up and use six instead?

**Comment by c3V6a2Vy** [comment]
That's on my list :)

I don't know much of six but I do really want to stick with the latest, I will do more research.

**Comment by wsidl** [comment]
Biggest suggestion is to use six's u() method. It will convert a "regular" string object to an unicode variant (Python 2 being unicode, Python 3 being str)

https://six.readthedocs.io/#six.u

**Comment by wsidl** [comment]
There shouldn't be a lot to do here and may be able to do it myself.

**Comment by c3V6a2Vy** [comment]
bear with me on this matter, I am totally new to the whole Python2 <> Python3 compatibility (we Java folks don't have that problem) but I do want to learn.

Are you suggesting replacing:

`bytedata = bytearray("%s\r"%(strcmd.strip()))`

with 

`bytedata = bytearray(six.u("%s\r"%(strcmd.strip())), 'utf8')`?

I can see the `bytearray()` function works in [Python3](https://docs.python.org/3/library/functions.html#func-bytearray) as well.

**Comment by c3V6a2Vy** [comment]
https://github.com/c3V6a2Vy/pyanova/pull/7

Can you please take a look?

**Comment by wsidl** [comment]
I can take a look. I've started a local branch from your new branch with a number of other changes (mostly syntax updates and for testing locally).

Another suggestion is using Format strings instead of printf strings as future versions support them better.
